# Generated by Django 5.0.6 on 2024-06-16 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter_name', models.CharField(max_length=25)),
                ('transporter_contact', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=40)),
                ('destination', models.CharField(max_length=40)),
                ('destination_link', models.CharField(max_length=50)),
                ('number_of_vehicles', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_limit', models.DateTimeField()),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transporters', models.ManyToManyField(to='app.transporterdetails')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_description', models.TextField()),
                ('vehicle_index', models.IntegerField()),
                ('material_weight', models.IntegerField()),
                ('material_height', models.IntegerField()),
                ('material_width', models.IntegerField()),
                ('material_length', models.IntegerField()),
                ('additional_details', models.TextField()),
                ('delivery_estimation', models.IntegerField()),
                ('loading_date', models.DateField()),
                ('loading_type', models.CharField(choices=[('ptl', 'Part Truck Load'), ('ftl', 'Full Truck Load')], max_length=5)),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.destinationdetail')),
            ],
        ),
        migrations.CreateModel(
            name='TransporterToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.destinationdetail')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transporterdetails')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicledetails')),
            ],
        ),
    ]
