# Generated by Django 5.0.6 on 2024-06-09 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_destinationdetail_pickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_description', models.TextField()),
                ('material_weight', models.IntegerField()),
                ('material_height', models.IntegerField()),
                ('material_width', models.IntegerField()),
                ('material_length', models.IntegerField()),
                ('additional_details', models.TextField()),
                ('delivery_estimation', models.IntegerField()),
                ('loading_date', models.DateTimeField()),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.destinationdetail')),
            ],
        ),
    ]
