# Generated by Django 5.0.6 on 2024-06-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_vehicledetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationdetail',
            name='destination',
            field=models.CharField(max_length=10),
        ),
    ]
