# Generated by Django 5.0.6 on 2024-06-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_destinationdetail_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetails',
            name='vehicle_index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
