# Generated by Django 5.0.6 on 2024-06-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_vehicledetails_vehicle_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetails',
            name='loading_type',
            field=models.CharField(choices=[('ptl', 'Part Truck Load'), ('ftl', 'Full Truck Load')], default='ptl', max_length=5),
            preserve_default=False,
        ),
    ]
