# Generated by Django 5.0.6 on 2024-06-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_destinationdetail_time_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetails',
            name='loading_date',
            field=models.DateField(),
        ),
    ]
