# Generated by Django 5.0.6 on 2024-06-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_vehicledetails_loading_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationdetail',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
