# Generated by Django 5.0.6 on 2024-06-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_destinationdetail_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter_name', models.CharField(max_length=25)),
                ('transporter_contact', models.IntegerField(unique=True)),
            ],
        ),
    ]
