# Generated by Django 5.0.6 on 2024-06-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_transporterdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporterdetails',
            name='transporter_contact',
            field=models.BigIntegerField(unique=True),
        ),
    ]
