# Generated by Django 5.0.6 on 2024-06-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_transporterdetails_transporter_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationdetail',
            name='transporters',
            field=models.ManyToManyField(to='app.transporterdetails'),
        ),
    ]
