# Generated by Django 5.0.6 on 2024-06-16 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_transportertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportertoken',
            name='transporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transporterdetails'),
        ),
    ]
